const currencyData = [
"Albanian Lek",
"Algerian Dinar",
"Euro",
"Angolan Kwanza",
"East Caribbean Dollar",
"Argentine Peso",
"Armenian Dram",
"Aruban Florin",
"Australian Dollar",
"Azerbaijan Manat",
"Bahamian Dollar",
"Bahraini Dinar",
"Bangladeshi Taka",
"Barbados Dollar",
"Belarusian Ruble",
"replaced Belgium Francs",
"Belize Dollar",
"CFA Franc BCEAO",
"Bermudian Dollar",
"Bhutanese Ngultrum",
"Indian Rupee",
"Boliviano",
"Convertible Mark",
"Pula",
"Brazilian Real",
"Brunei Dollar",
"Bulgarian Lev",
"CFA Franc BCEAO",
"Burundi Franc",
"Cambodian Riel ",
"CFA Franc BEAC",
"Canadian Dollar",
"Cape Verde Escudo",
"Cayman Islands Dollar",
"CFA Franc BEAC",
"Chilean Peso",
"Renminbi (Yuan)",
"Australian Dollar",
"Colombian Peso",
"Comoro Franc",
"Franc Congolais",
"CFA Franc BEAC",
"New Zealand Dollar",
"Costa Rican Colón",
"CFA Franc BCEAO",
"Croatian Kuna",
"Cuban Peso",
"Czech Koruna",
"Danish Kroner",
"US Dollar",
"Djibouti Franc",
"East Caribbean Dollar",
"Dominican Peso",
"Egyptian Pound",
"CFA Franc BEAC",
"Nakfa",
"Euro replaced Estonian Kroon in 2011.",
"Ethiopian Birr",
"Falkland Islands pound",
"Fiji Dollar",
"CFP Franc",
"CFA Franc BEAC",
"Dalasi",
"Lari",
"Cedi",
"Gibraltar Pound",
"replaced Drachma",
"Danish Krone",
"East Caribbean Dollar",
"Quetzal",
"Guinea Franc",
"Guinea-Bissau Peso",
"CFA Franc BCEAO",
"Guyana Dollar",
"Haitian Gourde",
"replaced Lira",
"Lempira",
"Hong Kong Dollar",
"Forint",
"Iceland Krona",
"Indian Rupee",
"Rupiah",
"Iranian Rial",
"Iraqi Dinar",
"New Israeli Sheqel",
"replaced Lira",
"Jamaican Dollar",
"Yen",
"Jordanian Dinar",
"Tenge",
"Kenyan Shilling",
"Australian Dollar",
"North Korean Won",
"Won",
"Kuwaiti Dinar",
"Som",
"Kip",
"Lebanese Pound",
"Liberian Dollar",
"Lybian Dinar",
"Swiss Franc",
"Euro replaced Lithuanian Litas",
"replaced Luxembourg Franc",
"Macanese Pataca",
"Macedonian Denar",
"Malagasy Franc",
"Kwacha",
"Malaysian Ringgit",
"Rufiyaa",
"CFA Franc BCEAO",
"Maltese Lira",
"Ouguiya",
"Mauritius Rupee",
"Mexican Peso",
"Moldovan Leu",
"Mongolia Tughrik (Tugrik, Tugrug, tögrög)",
"East Caribbean Dollar",
"Moroccan Dirham",
"Mozambican Metical",
"Burmese Kyat",
"Namibia Dollar",
"South African Rand",
"Australian Dollar",
"Nepalese Rupee",
"Netherlands Antilles Guilder",
"CFP Franc (South Pacific Franc)",
"New Zealand Dollar",
"Nicaraguan Córdoba (córdoba oro)",
"West African CFA Franc",
"Nigerian Naira",
"New Zealand Dollar",
"Norwegian Krone",
"Omani Rial",
"Pakistan Rupee",
"Egyptian Pound",
"Israeli New Shekel",
"Jordanian Dinar",
"Panamanian Balboa",
"Papua New Guinean Kina",
"Paraguayan Guarani",
"Peruvian (Nuevo) Sol",
"Philippine Peso",
"New Zealand Dollar",
"Polish Zloty (złoty)",
"Qatari Rial",
"Leu",
"Russian Ruble",
"Rwanda Franc",
"Saint Helena Pound",
"East Caribbean Dollar",
"Tala",
"Dobra",
"Saudi Riyal",
"CFA Franc BCEAO",
"Serbian Dinar",
"Seychelles Rupee",
"Leone",
"Singapore Dollar",
"replaced Slovak Koruna",
"replaced Slovenian Tolar",
"Solomon Islands Dollar",
"Somali Shilling",
"Rand",
"South Sudanese pound",
"replaced Spanish Peseta",
"Sri Lanka Rupee",
"Sudanese Dinar [obsolete]",
"Suriname Guilder",
"Lilangeni",
"Swedish Krona",
"Swiss Franc",
"Syrian Pound",
"New Taiwan Dollar",
"Somoni",
"Tanzanian Shilling",
"Thai Baht",
"CFA Franc BCEAO",
"New Zealand Dollar",
"Paʻanga",
"Trinidad and Tobago Dollar",
"Tunisian Dinar",
"Yeni Türk Liras (TRL)",
"Manat",
"Australian Dollar",
"Uganda Shilling",
"Ukrainian Hryvnia",
"UAE Dirham",
"Pound Sterling",
"US Dollar r (Same day)",
"US Dollar r (Next day)",
"Uruguayan Peso",
"Uzbekistan Sum",
"Vanuatu Vatu",
"Venezuelan Bolívar",
"Vietnamese Dong",
"CFP Franc",
"Moroccan Dirham",
"Yemeni Rial",
"Zambian Kwacha ",
]
export default currencyData